Correct icarMedicineResource syntax
adewg/ICAR pull request #169
Opened 2020-10-16 04:59 UTC by cookeac

- correct reference to **icarResource.json**
- correct *registeredID* to reference **icarMedicineIdentifierType.json**

Fixes #167

2020-10-20 12:53 UTC, ahokkonen requested changes

2020-10-20 12:53 UTC, ahokkonen commented on resources/icarMedicineResource.json
> +            "$ref": "icarResource.json"
@cookeac I think this should point into "../resources/icarResource.json" as we agreed on using root relative paths

2020-10-21 02:44 UTC, cookeac commented on resources/icarMedicineResource.json
> +            "$ref": "icarResource.json"
Agreed.

2020-10-21 09:00 UTC, ahokkonen approved these changes

2020-10-21 09:00 UTC, merged