WIP: CoatColorDetails in IcarAnimalCoreResource
adewg/ICAR pull request #252
Opened 2021-09-29 11:30 UTC by AndreasSchultzGEA

2021-10-04 07:14 UTC, erwinspeybroeck approved these changes
Maybe we should add some example schemes in the Wiki. This has also been done for a number of other schemes --> https://github.com/adewg/ICAR/wiki/Schemes

2021-10-04 12:14 UTC, AndreasSchultzGEA commented
added Animals.CoatColor to https://github.com/adewg/ICAR/wiki/Schemes
Pls. have a look

2021-10-07 05:57 UTC, cookeac requested changes

2021-10-07 05:57 UTC, cookeac commented on resources/icarAnimalCoreResource.json
> +          "description": "Colour of the animal's coat, using the conventions for that specie."
I'd rather the description said "Colour of the animal's coat using a national or breed-defined scheme and identifier combination."

2021-10-07 19:35 UTC, cookeac approved these changes

2021-10-07 19:40 UTC, merged