added the withdrawal-resources and an example for an interface
adewg/ICAR pull request #320
Opened 2022-09-09 11:14 UTC by AndreasSchultzGEA

2022-09-12 05:48 UTC, cookeac requested changes
Suggesting a bit more detail in description to help people understand types of use cases. I also wondered if this should be just a resource or an event - I think either could work.

2022-09-12 05:48 UTC, cookeac commented on resources/icarWithdrawalResource.json
> +  "description": "Withdrawal resource to seperate a product.",
```suggestion
  "description": "A withdrawal resource used to indicate that product should be separated (e.g. colostrum from newly lactating cows).",
```

2022-09-12 05:48 UTC, cookeac commented on resources/icarWithdrawalResource.json
> +      "$ref": "../resources/icarResource.json"
Agree this could be a "resource", but it could also be an "event" with the event date being the start of separation, and simply specifying end date and product type (remark being already built into events). 
Either a resource or an event would work -- it just seemed more like another event to me?

2022-09-13 06:23 UTC, AndreasSchultzGEA commented on resources/icarWithdrawalResource.json
> +      "$ref": "../resources/icarResource.json"
changed from Resource to EventResource

2022-09-13 21:40 UTC, cookeac approved these changes
Looks good now.

2022-09-14 15:06 UTC, erwinspeybroeck approved these changes
also ok for me

2022-09-14 21:22 UTC, cookeac approved these changes

2022-09-15 06:11 UTC, cookeac requested changes
@AndreasSchultzGEA GitHub says that the branch has conflicts that must be resolved.
The issue is simply that the milkURLScheme.json in this PR has different tab indentation on its lines than that in the Develop branch. Therefore it looks like every line has changed, while in the meantime there have been minor changes to the version in the Develop branch. I think if you reformat this file with the smaller spacing that is in the existing file, it should merge fine.

Also there is a warning on line 519 - the "operation" for "get existing milking-withdrawals" must not have spaces (currently it does have spaces). 

I tried to make the changes and add them to your branch, but of course I don't have permission.

2022-09-16 06:22 UTC, AndreasSchultzGEA commented
finally, I re-fixed the formatting

2022-09-16 06:48 UTC, merged

2022-09-16 06:48 UTC, cookeac commented
Adds withdrawal resource, resolves #318