Added repro flushing event with type and enums
adewg/ICAR pull request #337
Opened 2022-10-18 22:05 UTC by cvigorsICBF

Submitting a flushing event with supporting type and enum for issue #296

2022-10-19 21:41 UTC, cookeac commented
Will also need to add the embryo flushing event to ExampleURLScheme and Reproduction URL scheme OAS files.
Better to do this in a separate PR after PR #336 is merged to avoid conflicts and manual merges.

2022-11-17 07:34 UTC, cookeac requested changes
Update the tags as discussed.

2022-11-17 07:34 UTC, cookeac commented on resources/icarReproEmbryoFlushingEventResource.json
> +        "flushingType": {
Would you consider renaming this field flushingMethod, and its corresponding enumeration to icarReproEmbryoFlushingMethodType.json? "Method" is more precise than "type" in this instance.

2022-11-17 07:34 UTC, cookeac commented on resources/icarReproEmbryoFlushingEventResource.json
> +            "$ref": "../types/icarReproPotentialSireIdentifierType.json"
Good. We should have defined a sire identifier type from the outset - it could have been incorporated in all the places where we have SireIdentifiers+SireOfficialName+SireURI. Given the field is called **potentialSires**, could the type just be called **icarReproSireIdentifierType.json** and then in time we can standardise its usage elsewhere (even in the mating recommendation, etc)?

2022-11-17 07:34 UTC, cookeac commented on url-schemes/exampleUrlScheme.json
> +          "ADE-1.3-reproduction"
```suggestion
          "ADE-1.4-reproduction"
```

2022-11-17 07:34 UTC, cookeac commented on url-schemes/reproductionURLScheme.json
> +                    "ADE-1.3-reproduction"
```suggestion
                    "ADE-1.4-reproduction"
```

2022-11-17 09:14 UTC, cvigorsICBF commented on url-schemes/reproductionURLScheme.json
> +                    "ADE-1.3-reproduction"
Change has been made to scheme

2022-11-17 09:14 UTC, cvigorsICBF commented on url-schemes/exampleUrlScheme.json
> +          "ADE-1.3-reproduction"
Requested change has been made to scheme

2022-11-22 04:36 UTC, cookeac approved these changes
Looks good.

2022-11-22 04:37 UTC, merged

2022-11-22 04:41 UTC, cookeac commented
Realised after pressing confirm merge that the target for this PR was the ADE1 branch, not the Develop branch. Have reverted and will need to reapply this PR to the Develop branch (once I figure out how).