#285 milk predictions
adewg/ICAR pull request #346
Opened 2022-11-09 17:40 UTC by erwinspeybroeck

Changed accordingly the remarks

2022-11-17 07:21 UTC, cookeac commented on resources/icarMilkPredictionResource.json
> +        "PredictedProductionNextMR": {
```suggestion
        "PredictedProductionNextMR": {
```
        "predictedProductionNextMR": {

2022-11-17 07:25 UTC, cookeac commented on resources/icarMilkPredictionResource.json
> +        "averagePredictedProduction": {
```suggestion
        "averageRemainingProduction": {
```

2022-11-17 07:26 UTC, cookeac commented on resources/icarTestDayResultEventResource.json
> +        "PredictedProductionOnTestday": {
```suggestion
        "predictedProductionOnTestday": {
```

2022-11-17 07:27 UTC, cookeac commented on types/icarMilkingFatWeightType.json
> +{
Remove this file.

2022-11-17 07:29 UTC, cookeac commented on types/icarMilkingPredictionType.json
> +    "MilkWeight": {
Consider using icarMassMeasureType
Also check capitalisation.

2022-11-17 07:30 UTC, cookeac requested changes
@erwinspeybroeck to make the changes.

2022-11-22 15:53 UTC, erwinspeybroeck commented on types/icarMilkingPredictionType.json
> +      "$ref": "../types/icarMilkingMilkWeightType.json"
```suggestion
      "$ref": "../types/icarMassMeasureType.json"
```

2022-11-22 15:54 UTC, erwinspeybroeck commented on types/icarMilkingPredictionType.json
> +      "$ref": "../types/icarMilkingFatWeightType.json"
```suggestion
      "$ref": "../types/icarMassMeasureType.json"
```

2022-11-22 15:54 UTC, erwinspeybroeck commented on types/icarMilkingPredictionType.json
> +      "$ref": "../types/icarMilkingProteinWeightType.json"
```suggestion
      "$ref": "../types/icarMassMeasureType.json"
```

2022-11-22 15:57 UTC, erwinspeybroeck commented on resources/icarMilkPredictionResource.json
> +          "$ref": "../types/icarMilkingMilkWeightType.json"
```suggestion
          "$ref": "../types/icarMassMeasureType.json"
```

2023-03-09 08:11 UTC, cookeac requested changes
@erwinspeybroeck In addition to the few suggestions I have added in the files (you should be able to just accept/commit these), please consider:
1. Removing the changes to `icarStatisticsResource` and `icarStatisticsGroupType` as these are now corrected in the published ADE 1.3.2. Depending on how you are editing, you might choose to "stash" the files with the milk prediction changes, then refresh your branch from the Develop branch, and then put your milk prediction files back in.
2. In the URL schemes, for the moment just leave all the tags as "-1.3-" rather than 1.3.2 or 1.4. We will update all the tags in bulk before we publish version 1.4.

Thanks

2023-03-09 08:11 UTC, cookeac commented on types/icarMilkingPredictionType.json
> +    "MilkWeight": {
```suggestion
    "milkWeight": {
```

2023-03-09 08:11 UTC, cookeac commented on types/icarMilkingPredictionType.json
> +    "FatWeight": {
```suggestion
    "fatWeight": {
```

2023-03-09 08:11 UTC, cookeac commented on types/icarMilkingPredictionType.json
> +    "ProteinWeight": {
```suggestion
    "proteinWeight": {
```

2023-03-09 08:11 UTC, cookeac commented on types/icarMilkingPredictionType.json
> +    "Hours": {
```suggestion
    "hours": {
```

2023-03-09 08:11 UTC, cookeac commented on url-schemes/exampleUrlScheme.json
> +      "name": "ADE-1.4 additions",
```suggestion
      "name": "ADE-1.3 additions",
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on resources/icarStatisticsResource.json
> +        "$ref": "../types/icarStatisticsGroupType.json",
```suggestion
        "$ref": "../types/icarStatisticsGroupType.json"
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/exampleUrlScheme.json
> +      "name": "ADE-1.3.2-management",
```suggestion
      "name": "ADE-1.3-management",
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/exampleUrlScheme.json
> +                "ADE-1.4 additions"
```suggestion
                "ADE-1.3 additions"
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/exampleUrlScheme.json
> +                    "ADE-1.3.2-management"
```suggestion
                    "ADE-1.3-management"
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/managementURLScheme.json
> +            "name": "ADE-1.3.2-management",
```suggestion
            "name": "ADE-1.3-management",
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/managementURLScheme.json
> +                    "ADE-1.3.2-management"
```suggestion
                    "ADE-1.3-management"
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/milkURLScheme.json
> +          "name": "ADE-1.4-milk",
```suggestion
          "name": "ADE-1.3-milk",
```

2023-03-22 06:53 UTC, erwinspeybroeck commented on url-schemes/milkURLScheme.json
> +                    "ADE-1.4-milk"
```suggestion
                    "ADE-1.3-milk"
```

2023-03-22 08:29 UTC, erwinspeybroeck commented on url-schemes/milkURLScheme.json
> +          "name": "ADE-1.3-milk",
```suggestion
          "name": "ADE-1.4-milk",
```

2023-03-22 08:29 UTC, erwinspeybroeck commented on url-schemes/managementURLScheme.json
> +            "name": "ADE-1.3-management",
```suggestion
            "name": "ADE-1.4-management",
```

2023-03-23 07:39 UTC, closed without merging

2023-03-23 07:39 UTC, erwinspeybroeck commented
will not use it