Additional Metrics for Daily Milk Production Averages
adewg/ICAR pull request #397
Opened 2023-06-21 08:32 UTC by ArjanRovecom

This pull request aims to enhance the existing functionality by retrieving additional metrics related to daily milk production averages, including milk characteristics, feed consumption, and corresponding gestation days. These metrics provide valuable insights into the overall performance and health of dairy cattle.

2023-06-22 06:23 UTC, cookeac approved these changes
I agree with these, providing others are happy with the naming and meaning.

2023-06-22 06:35 UTC, erwinspeybroeck requested changes

2023-06-22 06:35 UTC, erwinspeybroeck commented on resources/icarLactationResource.json
gestationDays --> current days in gestation this day --> is it on the last test day or on the date the request for data is sent? I would presume the gestation days on the last test day?

2023-06-22 11:17 UTC, ArjanRovecom commented on resources/icarLactationResource.json
Because we expect that this data can also be provided from for example milking robots on a daily basis, we now assumed the data could be retrieved on the date the request for data is sent. Please let us know if this is a wrong assumption.

2023-06-22 11:19 UTC, ArjanRovecom commented
Added also property MilkingsEntitled in the icarDailyMilkingAveragesResource.json

This new data field aims to capture the number of milkings that a dairy cow is entitled to provide on a given day. By including this information in the standard, dairy farmers, veterinarians, and researchers can better manage cow welfare, optimize milk production, and make informed decisions regarding herd management

2023-06-29 07:24 UTC, cookeac commented on resources/icarLactationResource.json
@ArjanRovecom we discussed this at the ADE technical group meeting on 29 June 2023, and considered that:
- We would need a date in the data to know what date the `gestationDays` related to.
- We recommend that the `icarGestationResource` should be used for gestation data (but it may still be a good idea to add `gestationDays` and a date to this resource.

2023-06-29 07:27 UTC, cookeac commented on resources/icarLactationResource.json
@ArjanRovecom you would be welcome at our next ADE technical group meeting to help discuss this. It is at 08:15 CEST on 13 July 2023. Message me directly if you would like a Teams invite link.

2023-06-29 07:31 UTC, cookeac commented
We reviewed at the meeting on 29 June 2023. Overall this is looking good:
* We agree with the addition of `milkingsEntitled`
* We would like the `gestationDays` to be moved to the `icarGestationResource` and the date question will need to be addressed
* Hans Vogels will seek advice on the `feedResidues` value. We do think this is a good idea.

2024-05-02 05:51 UTC, erwinspeybroeck approved these changes
not completely comfortable with the gestationDays in the lactationresource, but it is not mandatory ...

2024-05-16 05:30 UTC, AlexeyHardCode approved these changes

2026-04-23 07:11 UTC, cookeac commented
Closing very old PR. Discussed with the group on 2026-04-23

2026-04-23 07:11 UTC, closed without merging