Develop
adewg/ICAR pull request #398
Opened 2023-06-28 14:48 UTC by cvigorsICBF

Changes to the icarReproHeatEvent to make it device independent

2023-06-29 07:22 UTC, cookeac requested changes
@cvigorsICBF we agreed at the meeting on 29 Jun 2023 that this looks great.
One suggestion please - add `"deprecated": true` to both the `heatReportScrSenseTime` and `heatReportNedapCowControl` sections, so that people know these should no longer be used.

2023-07-02 03:11 UTC, cookeac approved these changes

2023-07-03 07:21 UTC, erwinspeybroeck commented
No extra remarks from my side.

2023-07-03 07:22 UTC, erwinspeybroeck approved these changes

2023-07-03 08:07 UTC, merged