Add service-sires API - https://github.com/adewg/ICAR/issues/402
adewg/ICAR pull request #405
Opened 2023-07-28 06:59 UTC by erwinspeybroeck

https://github.com/adewg/ICAR/issues/402

2023-07-29 05:56 UTC, erwinspeybroeck commented on url-schemes/exampleUrlScheme.json
> +        "operationId": "get-service-sires for a given id",
"operationId": "get-service-sires for a given id" 
"operationId": "get-service-sires"

2023-08-10 05:28 UTC, cookeac requested changes
Looks good. In line with our discussion at the meeting, I'm suggesting a little more documentation so people know that only some fields will be populated.

2023-08-10 05:28 UTC, cookeac commented on url-schemes/exampleUrlScheme.json
> +        "description": "# Purpose\nProvides the service sires\n",
```suggestion
        "description": "# Purpose\nProvides the service sires.\nOnly animal fields relevant to service sires will be populated (location is not expected, for example).",
```

2023-08-10 07:15 UTC, erwinspeybroeck commented on url-schemes/exampleUrlScheme.json
> +        "summary": "Get the service sires matching your query parameters",
```suggestion
        "summary": "Get the service sires matching your query parameters - for now we only implement the query by some identifier, like lifetime number, ai-code, ... ",
```

2023-08-24 06:29 UTC, cookeac commented
Resolves #402

2023-08-24 06:29 UTC, merged