Sorting of animals
adewg/ICAR pull request #457
Opened 2024-04-15 05:20 UTC by AndreasSchultzGEA

Animals might have to be sorted on a farm.
Sorting in general is about getting animals from one area of a farm to another.
The way in between has to be managed by the HMS.
Therefore, a sorting-API should

deliver the sorting-areas of a location
deliver the currently active sorting-command for an animal
allow the inactivation of a sorting-command for an animal
allow the setting of a new sorting-command for an animal

2024-04-21 23:44 UTC, cookeac commented
This looks good. If this is approved I will also update #430 to allow site identifiers, optionally referring to the same sites.
One final question: might someone want to query all the active animal sorting commands for a location? If so, we would need a collection and API query for this.

2024-04-21 23:45 UTC, cookeac requested changes

2024-04-21 23:45 UTC, cookeac commented on resources/icarAnimalSortingCommandResource.json
> +        "animalId": {
```suggestion
        "animal": {
```

2024-04-21 23:45 UTC, cookeac commented on resources/icarAnimalSortingCommandResource.json
> +        "animalId": {
Suggesting we make this "animal" for consistency with other references (e.g. in the animal events).

2024-04-21 23:45 UTC, cookeac commented on resources/icarAnimalSortingCommandResource.json
> +        "siteId": {
```suggestion
        "site": {
```

2024-04-21 23:45 UTC, cookeac commented on resources/icarAnimalSortingCommandResource.json
> +        "siteId": {
If we made the other value into "animal", this could just be "site" with the description showing it is an identifier.

2024-04-21 23:45 UTC, cookeac commented on resources/icarAnimalSortingCommandResource.json
> +          "description": "Specifies until when the sort command should be active. Could be left empty, when the sorting should be permanent. RFC3339 UTC date time (see https://ijmacd.github.io/rfc333
```suggestion
          "description": "Specifies until when the sort command should be active. Could be left empty, when the sorting should be ongoing (until replaced). RFC3339 UTC date time (see https://ijmacd.github.io/rfc3339-iso8601/ for format guidance)."
```

2024-04-22 05:04 UTC, AndreasSchultzGEA commented
I added an endpoint to request al known sorting-commands.
@cookeac, could you please review the changes again?
Thx!

2024-04-22 05:04 UTC, cookeac commented on collections/icarAnimalSortingCommandCollection.json
> +          "description": "As per JSON-LD Hydra syntax, member provides the array of objects, in this case sorting-sites."
```suggestion
          "description": "As per JSON-LD Hydra syntax, member provides the array of objects, in this case animal sorting commands (icarAnimalSortingCommandResource)."
```

2024-04-22 05:05 UTC, cookeac approved these changes
Looks good to me.

2024-04-30 00:56 UTC, merged